name: Run MWE

on:
  pull_request:
  push:
    branches: [main]

jobs:
  mwe:
    name: Test on ${{ matrix.container }}
    runs-on: ubuntu-24.04
    container: ${{ matrix.container }}
    env:
      DEB_PYTHON_INSTALL_LAYOUT: deb_system

    strategy:
      fail-fast: false
      matrix:
        container: [
          "ghcr.io/fenics/dolfinx/dolfinx:stable",
          "ghcr.io/fenics/dolfinx/dolfinx:nightly",
        ]
    steps:
      - uses: actions/checkout@v4

      - name: Install package
        run: |
          python3 -m pip install adios4dolfinx

      - name: Run tests
        run: python3 mwe.py
